language: java
os: linux
sudo: false # faster builds

cache:
  directories:
  - "$HOME/.m2"

jdk: openjdk8

before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml

install: skip

script:
  - export MVN_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression="project.version" -q -DforceStdout)
  - echo "MVN_VERSION ${MVN_VERSION} - TRAVIS_TAG ${TRAVIS_BRANCH} - TRAVIS_BRANCH ${TRAVIS_BRANCH}"
  - mvn -B -V install

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "***** PRINT SUREFIRE REPORTS *****" && find . -type f -wholename "*/target/surefire-reports/*.txt" -exec cat {} \;
  - echo "***** PRINT FAILSAFE REPORTS *****" && find . -type f -wholename "*/target/failsafe-reports/*.txt" -exec cat {} \;

deploy:

  - provider: bintray
    skip_cleanup: true
    file: "target/bintray-deploy-descriptor.json"
    user: boddissattva
    key:
      secure: b5/LDneDufiGWw6h2W+zKkJpAJ4da4G83ZBvq3P7L6Y5cd/7V8W9zeaLz1PhnWTMtLGcF4SmBQIMoeG6wqI6OFUJptj9pqJQUpMcLXIpdG/QzV8YBsFYntX2wxpVxlCl6g2W16tMK6c6EwXK3n3egSPOkOhOYh3MBXQrbwipC3jTT9CdYLVJp3YKLiaxLPL1cKSo53mZMtuN4yNCQmOrXQEWjlT56H16LiSz5s5cvxc2QdQJ1aVoiD7hPJT0Cx0j/YyCiV9u5SiELlSJJxg29/X/RlbgHKLdpZQw1JAtyU8e4ojvx0vzUhqrFN9aPNioti5dUqU7vS6gWRCsENf4AX4Ol2lD5uisfRkJx4hm3R+/x0cBeCTb73zBrRkeB2Twh5Q73vzFbSmGndBObd+o3/Vir59LGsIyfP0yjQNS8Mx29fnyLUWjZ+cAABtL+ULXr+9AZUo8+JeTIb+MSNX1GZ021mYUEzLyiNB4p3J+yScYt07ypJLM6pFpUvu1Vkv42CnyCJYTjP6qUpbeYpFLZgkdKAM6albxDkikTOs0/CALf5EP4uTZfQsB1AXWKC4VRDpEbtQsurULe5sC2qiuARzz6rBQyHWM9xDyoKu7oaFGGsxQAbcOvUTTjfY010wbV6tqyChoMfaxQFrF+ZTj361jyDDZZPSBAgmSU2zFucE=
    on:
      repo: chutney-testing/chutney-junit
      all_branches: true
      tags: true
      condition: $MVN_VERSION = $TRAVIS_TAG

  - provider: releases
    skip_cleanup: true
    file_glob: true
    file:
      - "api/target/chutney-*.jar"
      - "engine/target/chutney-*.jar"
    api_key:
      secure: gY1JsqpYvRhuFzYE4OgDDOG+9cmvX1a8mPAcZ16bp/NouRXcyohViNnoE7/tuDffANVvSe5ru+qgHzjlxrZTDyuaXF4N5EFbTekcFplJKcQqsUm1UkYxEIOfUd7bhWc4nfoNtdXfkI1IldEz7g5oe9D96NusYkRO9yr6q3sOiooG35dhb2POiCU+rV2D2ec6GnBkrfwwWmxIeuzS5r20WkiPiAHJTGJNggqJ9MoK1fnf4qhUDP2TBX76UVcQh/Oh0KVMRb4ZuH6mCzHi5ifgAbRTyJzz15t5kkzXWKasOl1ZV5ueVzXh/+6zdULm9jmN+zn7TvB0ixpezRrghcJMUh3piiH95u5tcBvF4NlF+Zqg+SQH6UAtWYVgbFukTUXq4Wvt+oIdg0qs0Mqy5AkYpnEutjtRIhSrCtWvHQ9Q1IrIPxvx718TJHruEkW+RR5Wr5vMCnG3x4/QxR7T9rNXrhPK0lDKQsWxhM9j61CDpgBFT7tIvU8jWimAgD0hI54frChGTglT1EaqvYq7LXG/WE5/kKjxLGkViCaXTcHETmt0N7TdCkemQOWuo6PfBKgecR1kNqUfdsqk8HPilS921QetRoudcTKPPJKu1ipH0w9UZmCA49v1VkVBHEmtNvfuwaI6DQHFmF58pN/Bys4Hih1JqmPHrpL1Y/xoOzD1tDc=
    on:
      repo: chutney-testing/chutney-junit
      all_branches: true
      tags: true
      condition: $MVN_VERSION = $TRAVIS_TAG
